<?php include('header.php') ?>

<h1>The Birth of the Humans</h1>
<div class="article">
<p>In days long past, shortly after Eltara had become the heart of the universe, numerous portals to other worlds and times opened.  The first creatures to come through the gates raided the world.  The Seers and Speakers ended their war to unite against the raiders.  Together they successfully fended off raiders from many different realms and dimensions.  Then came the Myrae.  The Myrae had heard of the magical abilities of the Seers and Speakers and sought to have it for themselves to enhance their own natural abilities.  They began kidnapping all the sorcerers, trying to force their magical abilities from them.  When that didn’t work, they tried breeding with them, to try to take back with them children who could wield magic.  That, too, was unsuccessful, and many children died at the hands of the Myrae.  The rituals the Myrae used to try to steal magical ability almost always ended in the death of the magic user.  The Seers and Speakers opened a portal to an isolated dimension and many fled there.  Lioryn was grieved to see her children slaughtered, and withdrew deep within Eltara, taking all magic with her to prevent any more deaths.  For two more generations the Myrae sought and destroyed all who were reported to manipulate magic.</p>

<p>When the Myrae finally withdrew, believing they had eradicated all magic on Eltara since they themselves could not have it, the Seers and Speakers who were left, along with the half breed children left behind, tried to rebuild a life for themselves.  Soon the children saw the grief their presence caused the Seers and Speakers and they left their homes to form their own tribe.  They called themselves humans and over the next ten generations, they homogenized into a distinct race.  Gone was the Sight of the Seers, gone was the telepathy of the Speakers.  They gradually lost the third eye of the Seers, the skin-ribbons of the Speakers, and the monstrous size of the Myrae.  But for all they had lost, they developed a trait all their own.  They became adaptable.  The blood of the Seers and Speakers in them mingled with the magic of the Myrae to allow them to take on aspects of other creatures through ritual.  Some chose the amphibious lungs of lizards, some chose the long claws of wildcats, some chose the powerful noses of the dogs.</p>

<p>The humans preferred to think of themselves as Eltara’s third native race, equal to the Seers and Speakers.  And as other races came to Eltara, they learned that they could imitate them also.  And so was born the race known as human, with their talent for adaptability.</p>
</div> <!-- end .article -->
<?php include('footer.php') ?>
